### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gaurav-karna** [gaurav-karna/Tejas#15]
- [ ] Integrate Images + Backup to Drive
- [ ] Finish Admin Functions
- [ ] Finish Visitor Functions
- [ ] Set up emailing
- [ ] Come up with UI / Color scheme
